### ISSUE TITLE
Upload problem

### ISSUE THREAD

**Issue by hdsoftware001** [hdsoftware-official/edustrate#14]
i can`t upload files

**Comment by pixelpro15** [comment]
Oh, sorry! You need to create  a new branch and start a pull request. I’ll email you a video on how to do that.

**Comment by hdsoftware001** [comment]
Ok, thx

All the best,

Oliver

**Comment by pixelpro15** [comment]
Oliver, do you know what forking does?

I've emailed you a .zip file which contained a video which tells you how to use GitHub (Episode 1 please).
