### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by hdsoftware001** [hdsoftware-official/edustrate#15]
Isaac, can you please make me an owner so i can publish a update?

**Comment by pixelpro15** [comment]
Hi, Oliver,

Please publish a pull request, and we can review it. I just want to know
what you're updating before you update it.

I'll send you a video where you can see how it works.

Isaac

**Comment by pixelpro15** [comment]
[Click here to open the link. Download the .zip file to GitHub for Desktop, then open the GitHub folder of your Documents Library. If you can't get it to work, I'll send you a different link.](https://github.com/hdsoftware-official/video-series/blob/master/repo1%20v1.0.zip)

**Comment by pixelpro15** [comment]
Oops, wrong link!
[Try this,](https://github.com/hdsoftware-official/video-series/)
