### ISSUE TITLE
edustrate side bar

### ISSUE THREAD

**Issue by Niceygy** [hdsoftware-official/edustrate#18]
can you email me the code for the sidebar so i can add it to future code?

**Comment by Niceygy** [comment]
itt is hhere

**Comment by Niceygy** [comment]
isaac?

**Comment by pixelpro15** [comment]
Sorry, tech issues. I can't easily send you just the code - it relies on a custom Bootstrap framework. I need to make a package containing the HTML document and the CSS and JS files. Do you want just the `.child` one, or all of them (that's `.child`, `.parent` and `.teacher`)?

**Comment by Niceygy** [comment]
.child pls

**Comment by pixelpro15** [comment]
OK, I'll sort it tonight. I need to make our product video first, but I will do it.

On a slightly related note **DO NOT PUBLISH THAT VIDEO YET!**

**Comment by pixelpro15** [comment]
Just quickly reopening this. to send the .zip file. Linked below:

[Click here to download **package1.zip**, uploaded by pixelpro15.](https://github.com/hdsoftware-official/edustrate/files/4746496/package1.zip)

**Comment by pixelpro15** [comment]
(directed to @Niceygy who opened this)

**Comment by Niceygy** [comment]
thx @pixelpro15  it is perfect
